In [1]:
import torch

In [2]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [3]:
# transpose
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [22]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [5]:
points.is_contiguous()

True

In [24]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [7]:
points_t.is_contiguous()

False

In [8]:
points_t_cont = points_t.contiguous() # make contiguous
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [9]:
points_t_cont.is_contiguous()

True

In [10]:
# this storage is not the same as points.storage()
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [11]:
points.stride()

(2, 1)

In [12]:
points_t.stride()

(1, 2)

In [13]:
points_t_cont.stride()

(3, 1)

__Question__: Why are the id's of the storage of `points` and that of `points_t_cont` the same? That means one is the copy of another? Also, everytime I run the following cell, the id changes.

In [14]:
print(id(points.storage()))
print(id(points_t_cont.storage()))

4763644784
4763644784


__Although__, the `data_ptr()` are different, and they are the address of the the first element of the tensors. 

In [35]:
print(points.data_ptr())
print(points_t_cont.data_ptr())

140505611858112
140505617012608
