In [1]:
import torch

In [2]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [3]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [4]:
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [5]:
points.is_contiguous()

True

In [6]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [7]:
points_t.is_contiguous()

False

In [8]:
points_t_cont = points_t.contiguous() # make contiguous
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [9]:
points_t_cont.is_contiguous()

True

In [10]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

In [11]:
points.stride()

(2, 1)

In [12]:
points_t.stride()

(1, 2)

In [13]:
points_t_cont.stride()

(3, 1)

__Question__: Why are the id's of the storage of `points` and that of `points_t_cont` the same? That means one is the copy of another?

In [14]:
print(id(points.storage()))
print(id(points_t_cont.storage()))

4839828368
4839828368
